const CACHE='coco-bambu-v14-safe-layout';
self.addEventListener('install',e=>e.waitUntil(
  caches.open(CACHE).then(c=>c.addAll([
    './',
    './index.html',
    './manifest.json',
    '/escala-garcons/',
    '/escala-garcons/index.html',
    '/escala-garcons/manifest.json'
  ]).catch(()=>{}))
));
self.addEventListener('activate',e=>e.waitUntil(
  caches.keys().then(keys=>Promise.all(
    keys.filter(k=>k!==CACHE).map(k=>caches.delete(k))
  ))
));
self.addEventListener('fetch',e=>e.respondWith(
  fetch(e.request).catch(()=>caches.match(e.request))
));
