window.UNIFORMES_SEED = [
  {
    "id": "cozinha_pia_doma_cozinha_p",
    "setor": "COZINHA / PIA",
    "grupo": "DOMA BRANCA",
    "nome": "DOMA COZINHA P",
    "tipo": "Doma",
    "tamanho": "P",
    "estoqueAtual": 0,
    "ideal": 8,
    "minimo": 2,
    "comprar": 8,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_doma_cozinha_m",
    "setor": "COZINHA / PIA",
    "grupo": "DOMA BRANCA",
    "nome": "DOMA COZINHA M",
    "tipo": "Doma",
    "tamanho": "M",
    "estoqueAtual": 2,
    "ideal": 10,
    "minimo": 2,
    "comprar": 8,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_doma_cozinha_g",
    "setor": "COZINHA / PIA",
    "grupo": "DOMA BRANCA",
    "nome": "DOMA COZINHA G",
    "tipo": "Doma",
    "tamanho": "G",
    "estoqueAtual": 6,
    "ideal": 10,
    "minimo": 2,
    "comprar": 4,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_doma_cozinha_gg",
    "setor": "COZINHA / PIA",
    "grupo": "DOMA BRANCA",
    "nome": "DOMA COZINHA GG",
    "tipo": "Doma",
    "tamanho": "GG",
    "estoqueAtual": 0,
    "ideal": 4,
    "minimo": 1,
    "comprar": 4,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_doma_cozinha_extra_x_g",
    "setor": "COZINHA / PIA",
    "grupo": "DOMA BRANCA",
    "nome": "DOMA COZINHA EXTRA X G",
    "tipo": "Doma",
    "tamanho": "G",
    "estoqueAtual": 4,
    "ideal": 4,
    "minimo": 1,
    "comprar": 0,
    "status": "OK",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_calca_branca_p",
    "setor": "COZINHA / PIA",
    "grupo": "CALÇA BRANCA COZINHA",
    "nome": "CALÇA BRANCA P",
    "tipo": "Calça",
    "tamanho": "P",
    "estoqueAtual": 0,
    "ideal": 8,
    "minimo": 2,
    "comprar": 8,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_calca_branca_m",
    "setor": "COZINHA / PIA",
    "grupo": "CALÇA BRANCA COZINHA",
    "nome": "CALÇA BRANCA M",
    "tipo": "Calça",
    "tamanho": "M",
    "estoqueAtual": 2,
    "ideal": 10,
    "minimo": 2,
    "comprar": 8,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_calca_branca_g",
    "setor": "COZINHA / PIA",
    "grupo": "CALÇA BRANCA COZINHA",
    "nome": "CALÇA BRANCA G",
    "tipo": "Calça",
    "tamanho": "G",
    "estoqueAtual": 6,
    "ideal": 10,
    "minimo": 2,
    "comprar": 4,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_calca_branca_gg",
    "setor": "COZINHA / PIA",
    "grupo": "CALÇA BRANCA COZINHA",
    "nome": "CALÇA BRANCA GG",
    "tipo": "Calça",
    "tamanho": "GG",
    "estoqueAtual": 0,
    "ideal": 4,
    "minimo": 1,
    "comprar": 4,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_calca_branca_x_gg",
    "setor": "COZINHA / PIA",
    "grupo": "CALÇA BRANCA COZINHA",
    "nome": "CALÇA BRANCA X GG",
    "tipo": "Calça",
    "tamanho": "XGG",
    "estoqueAtual": 4,
    "ideal": 4,
    "minimo": 1,
    "comprar": 0,
    "status": "OK",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_calca_xadrez_m",
    "setor": "COZINHA / PIA",
    "grupo": "CALÇA BRANCA COZINHA",
    "nome": "CALÇA XADREZ M",
    "tipo": "Calça",
    "tamanho": "M",
    "estoqueAtual": 0,
    "ideal": 4,
    "minimo": 1,
    "comprar": 4,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_calca_xadrez_g",
    "setor": "COZINHA / PIA",
    "grupo": "CALÇA BRANCA COZINHA",
    "nome": "CALÇA XADREZ G",
    "tipo": "Calça",
    "tamanho": "G",
    "estoqueAtual": 0,
    "ideal": 4,
    "minimo": 1,
    "comprar": 4,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_calca_azul_p",
    "setor": "COZINHA / PIA",
    "grupo": "CALÇA PIEIRO AZUL",
    "nome": "CALÇA AZUL P",
    "tipo": "Calça",
    "tamanho": "P",
    "estoqueAtual": 1,
    "ideal": 8,
    "minimo": 2,
    "comprar": 7,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_calca_azul_m",
    "setor": "COZINHA / PIA",
    "grupo": "CALÇA PIEIRO AZUL",
    "nome": "CALÇA AZUL M",
    "tipo": "Calça",
    "tamanho": "M",
    "estoqueAtual": 3,
    "ideal": 8,
    "minimo": 2,
    "comprar": 5,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_calca_azul_g",
    "setor": "COZINHA / PIA",
    "grupo": "CALÇA PIEIRO AZUL",
    "nome": "CALÇA AZUL G",
    "tipo": "Calça",
    "tamanho": "G",
    "estoqueAtual": 4,
    "ideal": 6,
    "minimo": 2,
    "comprar": 2,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_calca_azul_gg",
    "setor": "COZINHA / PIA",
    "grupo": "CALÇA PIEIRO AZUL",
    "nome": "CALÇA AZUL GG",
    "tipo": "Calça",
    "tamanho": "GG",
    "estoqueAtual": 2,
    "ideal": 4,
    "minimo": 1,
    "comprar": 2,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_calca_azul_xg",
    "setor": "COZINHA / PIA",
    "grupo": "CALÇA PIEIRO AZUL",
    "nome": "CALÇA AZUL XG",
    "tipo": "Calça",
    "tamanho": "XG",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_doma_azu_p",
    "setor": "COZINHA / PIA",
    "grupo": "DOMA PIEIRO AZUL",
    "nome": "DOMA AZU P",
    "tipo": "Doma",
    "tamanho": "P",
    "estoqueAtual": 0,
    "ideal": 8,
    "minimo": 2,
    "comprar": 8,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_camisa_azu_m",
    "setor": "COZINHA / PIA",
    "grupo": "DOMA PIEIRO AZUL",
    "nome": "CAMISA AZU M",
    "tipo": "Doma",
    "tamanho": "M",
    "estoqueAtual": 0,
    "ideal": 8,
    "minimo": 2,
    "comprar": 8,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_camisa_azu_g",
    "setor": "COZINHA / PIA",
    "grupo": "DOMA PIEIRO AZUL",
    "nome": "CAMISA AZU G",
    "tipo": "Doma",
    "tamanho": "G",
    "estoqueAtual": 0,
    "ideal": 6,
    "minimo": 2,
    "comprar": 6,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_camisa_azu_gg",
    "setor": "COZINHA / PIA",
    "grupo": "DOMA PIEIRO AZUL",
    "nome": "CAMISA AZU GG",
    "tipo": "Doma",
    "tamanho": "GG",
    "estoqueAtual": 1,
    "ideal": 4,
    "minimo": 1,
    "comprar": 3,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cozinha_pia_camisa_azu_xg",
    "setor": "COZINHA / PIA",
    "grupo": "DOMA PIEIRO AZUL",
    "nome": "CAMISA AZU XG",
    "tipo": "Doma",
    "tamanho": "XG",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "bar_bandana",
    "setor": "BAR",
    "grupo": "BAR",
    "nome": "BANDANA",
    "tipo": "Uniforme",
    "tamanho": "ÚNICO",
    "estoqueAtual": 6,
    "ideal": 10,
    "minimo": 2,
    "comprar": 4,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "bar_camisa_preta_social_manga_longa_p",
    "setor": "BAR",
    "grupo": "BAR",
    "nome": "CAMISA PRETA SOCIAL MANGA LONGA P",
    "tipo": "Uniforme",
    "tamanho": "P",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "bar_camisa_preta_social_manga_longa_m",
    "setor": "BAR",
    "grupo": "BAR",
    "nome": "CAMISA PRETA SOCIAL MANGA LONGA M",
    "tipo": "Uniforme",
    "tamanho": "M",
    "estoqueAtual": 0,
    "ideal": 4,
    "minimo": 1,
    "comprar": 4,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "bar_camisa_preta_social_manga_longa_g",
    "setor": "BAR",
    "grupo": "BAR",
    "nome": "CAMISA PRETA SOCIAL MANGA LONGA G",
    "tipo": "Uniforme",
    "tamanho": "G",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "bar_colete_bar_p",
    "setor": "BAR",
    "grupo": "COLETE BAR",
    "nome": "COLETE BAR P",
    "tipo": "Colete",
    "tamanho": "P",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "bar_colete_bar_m",
    "setor": "BAR",
    "grupo": "COLETE BAR",
    "nome": "COLETE BAR M",
    "tipo": "Colete",
    "tamanho": "M",
    "estoqueAtual": 0,
    "ideal": 4,
    "minimo": 1,
    "comprar": 4,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "bar_colete_bar_g",
    "setor": "BAR",
    "grupo": "COLETE BAR",
    "nome": "COLETE BAR G",
    "tipo": "Colete",
    "tamanho": "G",
    "estoqueAtual": 5,
    "ideal": 2,
    "minimo": 1,
    "comprar": 0,
    "status": "OK",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "bar_colete_bar_g_g",
    "setor": "BAR",
    "grupo": "COLETE BAR",
    "nome": "COLETE BAR G G",
    "tipo": "Colete",
    "tamanho": "GG",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "bar_calca_p",
    "setor": "BAR",
    "grupo": "CALÇA PARA CUMIM E BAR OXFOR PRETA COM ELASTICO ATRAS",
    "nome": "CALÇA P",
    "tipo": "Calça",
    "tamanho": "P",
    "estoqueAtual": 0,
    "ideal": 8,
    "minimo": 2,
    "comprar": 8,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "bar_calca_m",
    "setor": "BAR",
    "grupo": "CALÇA PARA CUMIM E BAR OXFOR PRETA COM ELASTICO ATRAS",
    "nome": "CALÇA M",
    "tipo": "Calça",
    "tamanho": "M",
    "estoqueAtual": 3,
    "ideal": 10,
    "minimo": 2,
    "comprar": 7,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "bar_calca_g",
    "setor": "BAR",
    "grupo": "CALÇA PARA CUMIM E BAR OXFOR PRETA COM ELASTICO ATRAS",
    "nome": "CALÇA G",
    "tipo": "Calça",
    "tamanho": "G",
    "estoqueAtual": 5,
    "ideal": 10,
    "minimo": 2,
    "comprar": 5,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "bar_gravata_borboleta_preta",
    "setor": "BAR",
    "grupo": "BAR",
    "nome": "GRAVATA BORBOLETA PRETA",
    "tipo": "Uniforme",
    "tamanho": "ÚNICO",
    "estoqueAtual": 2,
    "ideal": 8,
    "minimo": 2,
    "comprar": 6,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "bar_suspensorio",
    "setor": "BAR",
    "grupo": "BAR",
    "nome": "SUSPENSÓRIO",
    "tipo": "Uniforme",
    "tamanho": "ÚNICO",
    "estoqueAtual": 4,
    "ideal": 8,
    "minimo": 2,
    "comprar": 4,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cumim_avental_preto_cumim",
    "setor": "CUMIM",
    "grupo": "CAMISA CUMIM",
    "nome": "AVENTAL PRETO CUMIM",
    "tipo": "Camisa",
    "tamanho": "ÚNICO",
    "estoqueAtual": 6,
    "ideal": 10,
    "minimo": 2,
    "comprar": 4,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cumim_camisa_preta_manga_curta_p",
    "setor": "CUMIM",
    "grupo": "CAMISA CUMIM",
    "nome": "CAMISA PRETA MANGA CURTA P",
    "tipo": "Camisa",
    "tamanho": "P",
    "estoqueAtual": 0,
    "ideal": 10,
    "minimo": 2,
    "comprar": 10,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cumim_camisa_preta_manga_curta_m",
    "setor": "CUMIM",
    "grupo": "CAMISA CUMIM",
    "nome": "CAMISA PRETA MANGA CURTA M",
    "tipo": "Camisa",
    "tamanho": "M",
    "estoqueAtual": 0,
    "ideal": 15,
    "minimo": 4,
    "comprar": 15,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cumim_camisa_preta_manga_curta_g",
    "setor": "CUMIM",
    "grupo": "CAMISA CUMIM",
    "nome": "CAMISA PRETA MANGA CURTA G",
    "tipo": "Camisa",
    "tamanho": "G",
    "estoqueAtual": 0,
    "ideal": 6,
    "minimo": 2,
    "comprar": 6,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "cumim_camisa_preta_manga_curta_gg",
    "setor": "CUMIM",
    "grupo": "CAMISA CUMIM",
    "nome": "CAMISA PRETA MANGA CURTA GG",
    "tipo": "Camisa",
    "tamanho": "GG",
    "estoqueAtual": 4,
    "ideal": 4,
    "minimo": 1,
    "comprar": 0,
    "status": "OK",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "administrativo_caixa_delivery_camisa_polo_azul_escuro_p",
    "setor": "ADMINISTRATIVO / CAIXA / DELIVERY",
    "grupo": "ESCRITÓRIO/COMPRAS CAIXA E DELIVERY CAMISA POLO AZUL ESCURO",
    "nome": "CAMISA POLO AZUL ESCURO P",
    "tipo": "Camisa",
    "tamanho": "P",
    "estoqueAtual": 0,
    "ideal": 4,
    "minimo": 1,
    "comprar": 4,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "administrativo_caixa_delivery_camisa_polo_azul_escuro_m",
    "setor": "ADMINISTRATIVO / CAIXA / DELIVERY",
    "grupo": "ESCRITÓRIO/COMPRAS CAIXA E DELIVERY CAMISA POLO AZUL ESCURO",
    "nome": "CAMISA POLO AZUL ESCURO M",
    "tipo": "Camisa",
    "tamanho": "M",
    "estoqueAtual": 0,
    "ideal": 6,
    "minimo": 2,
    "comprar": 6,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "administrativo_caixa_delivery_camisa_polo_azul_escuro_g",
    "setor": "ADMINISTRATIVO / CAIXA / DELIVERY",
    "grupo": "ESCRITÓRIO/COMPRAS CAIXA E DELIVERY CAMISA POLO AZUL ESCURO",
    "nome": "CAMISA POLO AZUL ESCURO G",
    "tipo": "Camisa",
    "tamanho": "G",
    "estoqueAtual": 0,
    "ideal": 6,
    "minimo": 2,
    "comprar": 6,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "administrativo_caixa_delivery_camisa_polo_azul_escuro_gg",
    "setor": "ADMINISTRATIVO / CAIXA / DELIVERY",
    "grupo": "ESCRITÓRIO/COMPRAS CAIXA E DELIVERY CAMISA POLO AZUL ESCURO",
    "nome": "CAMISA POLO AZUL ESCURO GG",
    "tipo": "Camisa",
    "tamanho": "GG",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "asg_bata_feminina_p",
    "setor": "ASG",
    "grupo": "ASG",
    "nome": "BATA FEMININA P",
    "tipo": "Uniforme",
    "tamanho": "P",
    "estoqueAtual": 2,
    "ideal": 4,
    "minimo": 1,
    "comprar": 2,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "asg_bata_feminina_m",
    "setor": "ASG",
    "grupo": "ASG",
    "nome": "BATA FEMININA M",
    "tipo": "Uniforme",
    "tamanho": "M",
    "estoqueAtual": 2,
    "ideal": 4,
    "minimo": 1,
    "comprar": 2,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "asg_bata_feminina_g",
    "setor": "ASG",
    "grupo": "ASG",
    "nome": "BATA FEMININA G",
    "tipo": "Uniforme",
    "tamanho": "G",
    "estoqueAtual": 1,
    "ideal": 2,
    "minimo": 1,
    "comprar": 1,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "asg_bata_feminina_gg",
    "setor": "ASG",
    "grupo": "ASG",
    "nome": "BATA FEMININA GG",
    "tipo": "Uniforme",
    "tamanho": "GG",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "asg_calca_feminina_p",
    "setor": "ASG",
    "grupo": "CALÇA FEMININA ASG",
    "nome": "CAlCA FEMININA P",
    "tipo": "Calça",
    "tamanho": "P",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "asg_calca_feminina_m",
    "setor": "ASG",
    "grupo": "CALÇA FEMININA ASG",
    "nome": "CAlCA FEMININA M",
    "tipo": "Calça",
    "tamanho": "M",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "asg_cacca_feminina_g",
    "setor": "ASG",
    "grupo": "CALÇA FEMININA ASG",
    "nome": "CAÇCA FEMININA G",
    "tipo": "Calça",
    "tamanho": "G",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "asg_calca_feminina_gg",
    "setor": "ASG",
    "grupo": "CALÇA FEMININA ASG",
    "nome": "CALÇA FEMININA GG",
    "tipo": "Calça",
    "tamanho": "GG",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "asg_calca_feminina_extra_gg",
    "setor": "ASG",
    "grupo": "CALÇA FEMININA ASG",
    "nome": "CALÇA FEMININA EXTRA GG",
    "tipo": "Calça",
    "tamanho": "EXTRA GG",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "recepcao_blazer_oxfor_p",
    "setor": "RECEPÇÃO",
    "grupo": "RECEPÇÃO",
    "nome": "BLAZER OXFOR P",
    "tipo": "Uniforme",
    "tamanho": "P",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "recepcao_blazer_oxfor_m",
    "setor": "RECEPÇÃO",
    "grupo": "RECEPÇÃO",
    "nome": "BLAZER OXFOR M",
    "tipo": "Uniforme",
    "tamanho": "M",
    "estoqueAtual": 0,
    "ideal": 4,
    "minimo": 1,
    "comprar": 4,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "recepcao_blazer_oxfor_g",
    "setor": "RECEPÇÃO",
    "grupo": "RECEPÇÃO",
    "nome": "BLAZER OXFOR G",
    "tipo": "Uniforme",
    "tamanho": "G",
    "estoqueAtual": 4,
    "ideal": 2,
    "minimo": 1,
    "comprar": 0,
    "status": "OK",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "recepcao_blazer_oxfor_gg",
    "setor": "RECEPÇÃO",
    "grupo": "RECEPÇÃO",
    "nome": "BLAZER OXFOR GG",
    "tipo": "Uniforme",
    "tamanho": "GG",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "recepcao_camisa_social_oxfor_branca_sem_bordado_manga_longa_p",
    "setor": "RECEPÇÃO",
    "grupo": "CAMISA RECEPÇÃO",
    "nome": "CAMISA SOCIAL OXFOR BRANCA SEM BORDADO MANGA LONGA P",
    "tipo": "Camisa",
    "tamanho": "P",
    "estoqueAtual": 2,
    "ideal": 4,
    "minimo": 1,
    "comprar": 2,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "recepcao_camisa_social_oxfor_branca_sem_bordado_manga_longa_m",
    "setor": "RECEPÇÃO",
    "grupo": "CAMISA RECEPÇÃO",
    "nome": "CAMISA SOCIAL OXFOR BRANCA SEM BORDADO MANGA LONGA M",
    "tipo": "Camisa",
    "tamanho": "M",
    "estoqueAtual": 0,
    "ideal": 4,
    "minimo": 1,
    "comprar": 4,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "recepcao_camisa_social_oxfor_branca_sem_bordado_manga_longa_g",
    "setor": "RECEPÇÃO",
    "grupo": "CAMISA RECEPÇÃO",
    "nome": "CAMISA SOCIAL OXFOR BRANCA SEM BORDADO MANGA LONGA G",
    "tipo": "Camisa",
    "tamanho": "G",
    "estoqueAtual": 0,
    "ideal": 4,
    "minimo": 1,
    "comprar": 4,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "brinquedoteca_avental",
    "setor": "BRINQUEDOTECA",
    "grupo": "BRINQUEDOTECA",
    "nome": "AVENTAL",
    "tipo": "Uniforme",
    "tamanho": "ÚNICO",
    "estoqueAtual": 4,
    "ideal": 4,
    "minimo": 1,
    "comprar": 0,
    "status": "OK",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "brinquedoteca_camisa_brinquedoteca_p",
    "setor": "BRINQUEDOTECA",
    "grupo": "BRINQUEDOTECA",
    "nome": "CAMISA BRINQUEDOTECA P",
    "tipo": "Uniforme",
    "tamanho": "P",
    "estoqueAtual": 0,
    "ideal": 4,
    "minimo": 1,
    "comprar": 4,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "brinquedoteca_camisa_brinquedoteca_m",
    "setor": "BRINQUEDOTECA",
    "grupo": "BRINQUEDOTECA",
    "nome": "CAMISA BRINQUEDOTECA M",
    "tipo": "Uniforme",
    "tamanho": "M",
    "estoqueAtual": 0,
    "ideal": 4,
    "minimo": 1,
    "comprar": 4,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "brinquedoteca_camisa_brinquedoteca_g",
    "setor": "BRINQUEDOTECA",
    "grupo": "BRINQUEDOTECA",
    "nome": "CAMISA BRINQUEDOTECA G",
    "tipo": "Uniforme",
    "tamanho": "G",
    "estoqueAtual": 2,
    "ideal": 4,
    "minimo": 1,
    "comprar": 2,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "brinquedoteca_camisa_brinquedoteca_gg",
    "setor": "BRINQUEDOTECA",
    "grupo": "BRINQUEDOTECA",
    "nome": "CAMISA BRINQUEDOTECA GG",
    "tipo": "Uniforme",
    "tamanho": "GG",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "recepcao_lenco_laranja",
    "setor": "RECEPÇÃO",
    "grupo": "RECEPÇÃO",
    "nome": "LENÇO LARANJA",
    "tipo": "Uniforme",
    "tamanho": "ÚNICO",
    "estoqueAtual": 2,
    "ideal": 8,
    "minimo": 2,
    "comprar": 6,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "garcom_colete_avental",
    "setor": "GARÇOM",
    "grupo": "GARÇOM",
    "nome": "COLETE AVENTAL",
    "tipo": "Uniforme",
    "tamanho": "ÚNICO",
    "estoqueAtual": 10,
    "ideal": 20,
    "minimo": 5,
    "comprar": 10,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "garcom_gravata_laranja",
    "setor": "GARÇOM",
    "grupo": "GARÇOM",
    "nome": "GRAVATA LARANJA",
    "tipo": "Uniforme",
    "tamanho": "ÚNICO",
    "estoqueAtual": 9,
    "ideal": 20,
    "minimo": 5,
    "comprar": 11,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "garcom_gravata_preta_para_eventos",
    "setor": "GARÇOM",
    "grupo": "GARÇOM",
    "nome": "GRAVATA PRETA PARA EVENTOS",
    "tipo": "Uniforme",
    "tamanho": "ÚNICO",
    "estoqueAtual": 11,
    "ideal": 15,
    "minimo": 4,
    "comprar": 4,
    "status": "COMPRAR",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "garcom_camisa_branca_p",
    "setor": "GARÇOM",
    "grupo": "GARÇOM",
    "nome": "CAMISA BRANCA P",
    "tipo": "Uniforme",
    "tamanho": "P",
    "estoqueAtual": 0,
    "ideal": 6,
    "minimo": 2,
    "comprar": 6,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "garcom_camisa_branca_m",
    "setor": "GARÇOM",
    "grupo": "GARÇOM",
    "nome": "CAMISA BRANCA M",
    "tipo": "Uniforme",
    "tamanho": "M",
    "estoqueAtual": 0,
    "ideal": 20,
    "minimo": 5,
    "comprar": 20,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "garcom_camisa_branca_g",
    "setor": "GARÇOM",
    "grupo": "GARÇOM",
    "nome": "CAMISA BRANCA G",
    "tipo": "Uniforme",
    "tamanho": "G",
    "estoqueAtual": 0,
    "ideal": 20,
    "minimo": 5,
    "comprar": 20,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "garcom_camisa_branca_gg",
    "setor": "GARÇOM",
    "grupo": "GARÇOM",
    "nome": "CAMISA BRANCA GG",
    "tipo": "Uniforme",
    "tamanho": "GG",
    "estoqueAtual": 0,
    "ideal": 4,
    "minimo": 1,
    "comprar": 4,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "garcom_camisa_branca_xg",
    "setor": "GARÇOM",
    "grupo": "GARÇOM",
    "nome": "CAMISA BRANCA XG",
    "tipo": "Uniforme",
    "tamanho": "XG",
    "estoqueAtual": 0,
    "ideal": 4,
    "minimo": 1,
    "comprar": 4,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "almoxarifado_camisa_gabardine_cinza_p",
    "setor": "ALMOXARIFADO",
    "grupo": "ALMOXARIFADO",
    "nome": "CAMISA GABARDINE CINZA P",
    "tipo": "Uniforme",
    "tamanho": "P",
    "estoqueAtual": 2,
    "ideal": 2,
    "minimo": 1,
    "comprar": 0,
    "status": "OK",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "almoxarifado_camisa_gabardine_cinza_m",
    "setor": "ALMOXARIFADO",
    "grupo": "ALMOXARIFADO",
    "nome": "CAMISA GABARDINE CINZA M",
    "tipo": "Uniforme",
    "tamanho": "M",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "almoxarifado_camisa_gabardine_cinza_g",
    "setor": "ALMOXARIFADO",
    "grupo": "ALMOXARIFADO",
    "nome": "CAMISA GABARDINE CINZA G",
    "tipo": "Uniforme",
    "tamanho": "G",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "almoxarifado_calca_gabardine_cinza_p",
    "setor": "ALMOXARIFADO",
    "grupo": "ALMOXARIFADO",
    "nome": "CALÇA GABARDINE CINZA P",
    "tipo": "Uniforme",
    "tamanho": "P",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "almoxarifado_calca_gabardine_cinza_m",
    "setor": "ALMOXARIFADO",
    "grupo": "ALMOXARIFADO",
    "nome": "CALÇA GABARDINE CINZA M",
    "tipo": "Uniforme",
    "tamanho": "M",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "almoxarifado_calca_gabardine_cinza_g",
    "setor": "ALMOXARIFADO",
    "grupo": "ALMOXARIFADO",
    "nome": "CALÇA GABARDINE CINZA G",
    "tipo": "Uniforme",
    "tamanho": "G",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "almoxarifado_calca_gabardine_cinza_gg",
    "setor": "ALMOXARIFADO",
    "grupo": "ALMOXARIFADO",
    "nome": "CALÇA GABARDINE CINZA GG",
    "tipo": "Uniforme",
    "tamanho": "GG",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "controle_de_acesso_polo_preta_p",
    "setor": "CONTROLE DE ACESSO",
    "grupo": "CONTOLADOR DE ACESSO",
    "nome": "POLO PRETA P",
    "tipo": "Uniforme",
    "tamanho": "P",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "controle_de_acesso_polo_preta_m",
    "setor": "CONTROLE DE ACESSO",
    "grupo": "CONTOLADOR DE ACESSO",
    "nome": "POLO PRETA M",
    "tipo": "Uniforme",
    "tamanho": "M",
    "estoqueAtual": 0,
    "ideal": 4,
    "minimo": 1,
    "comprar": 4,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "controle_de_acesso_polo_preta_g",
    "setor": "CONTROLE DE ACESSO",
    "grupo": "CONTOLADOR DE ACESSO",
    "nome": "POLO PRETA G",
    "tipo": "Uniforme",
    "tamanho": "G",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "manutencao_polo_preta_p",
    "setor": "MANUTENÇÃO",
    "grupo": "MANUTENÇÃO",
    "nome": "POLO PRETA P",
    "tipo": "Uniforme",
    "tamanho": "P",
    "estoqueAtual": 2,
    "ideal": 2,
    "minimo": 1,
    "comprar": 0,
    "status": "OK",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  },
  {
    "id": "manutencao_polo_preta_m",
    "setor": "MANUTENÇÃO",
    "grupo": "MANUTENÇÃO",
    "nome": "POLO PRETA M",
    "tipo": "Uniforme",
    "tamanho": "M",
    "estoqueAtual": 0,
    "ideal": 2,
    "minimo": 1,
    "comprar": 2,
    "status": "ZERADO",
    "origem": "UNIFORMES ANAPOLIS 202666.xlsx"
  }
];
